#path_vectors: ./../../../test/data/embeddings/npy/

path_vector: ./../../../tmp/embeddings/
path_dataset: ./../../../test/data/benchmarks/similarity/
normalize: true
# specifies if embeddings should be normalized